import { EventItem } from '../_types';

export const events: EventItem[] = [
  {
    id: 'kagr-4th-annual',
    title: 'The 4th Annual KODING with KAGR',
    employer: 'The Kraft Group LLC',
    university: 'Boston University',
    featured: false,
    isEmployerHosted: true,
    medium: 'HYBRID',
    startDate: '2025-10-03T09:00:00-05:00',
    endDate: '2025-11-12T17:00:00-06:00',
    location: 'Hybrid',
    categories: ['GUIDANCE', 'NETWORKING'],
    tags: ['sports analytics', 'tech'],
    attendeesCount: 15,
    checkIns: 0,
    isSaved: false,
    isRegistered: false,
    logoUrl: '/logos/kraft-group.png',
  },
  {
    id: 'hs-virtual-office-hours',
    title: 'Virtual career planning office hours',
    employer: 'Handshake',
    university: 'Boston University',
    isEmployerHosted: false,
    medium: 'VIRTUAL',
    startDate: '2025-11-04T13:15:00-06:00',
    categories: ['GUIDANCE'],
    tags: ['career planning'],
    attendeesCount: 47,
    checkIns: 0,
    isSaved: true,
    isRegistered: true,
    logoUrl: '/logos/handshake.png',
  },
  {
    id: 'bu-avis-meet-greet',
    title: 'SHA Hiring: Meet & Greet with Avis Budget Group',
    employer: 'Boston University',
    university: 'Boston University',
    featured: true,
    isEmployerHosted: false,
    medium: 'IN_PERSON',
    startDate: '2025-11-03T10:45:00-06:00',
    location: 'SHA Lobby',
    categories: ['GUIDANCE', 'NETWORKING'],
    tags: ['hiring', 'resume'],
    attendeesCount: 0,
    checkIns: 0,
    isSaved: false,
    isRegistered: false,
    logoUrl: '/logos/bu.png',
  },
  {
    id: 'bu-resume-workshop-fy',
    title: 'Resume Workshop for First-Year Students',
    employer: 'Boston University',
    university: 'Boston University',
    featured: true,
    isEmployerHosted: false,
    medium: 'IN_PERSON',
    startDate: '2025-11-03T16:00:00-06:00',
    location: 'Career Center Room 220',
    categories: ['GUIDANCE', 'ACADEMIC'],
    tags: ['resume', 'workshop'],
    attendeesCount: 89,
    checkIns: 3,
    isSaved: false,
    isRegistered: true,
    logoUrl: '/logos/bu.png',
  },
  {
    id: 'signify-lighting-dev',
    title: 'Lighting Product Dev Jobs & Internships with Signify',
    employer: 'Signify (Philips Lighting)',
    isEmployerHosted: true,
    medium: 'IN_PERSON',
    startDate: '2025-11-04T16:00:00-06:00',
    location: 'Engineering Hall 104',
    categories: ['GUIDANCE'],
    tags: ['engineering', 'hardware'],
    attendeesCount: 22,
    checkIns: 0,
    isSaved: false,
    isRegistered: false,
    logoUrl: '/logos/signify.png',
  },
];
