/*import { CompanyEvent } from '../_types';

export const events: CompanyEvent[] = [
  {
    id: 'e1',
    title: 'Graduate Hiring Open House – Lahore',
    medium: 'IN_PERSON',
    location: 'Gulberg Office, Lahore',
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    endDate: '',
    status: 'published',
    createdAt: Date.now() - 1000 * 60 * 60 * 48,
    interestCount: 87,
    tags: ['hiring', 'networking'],
    featured: true,
  },
  {
    id: 'e2',
    title: 'Tech Internship AMA (Virtual)',
    medium: 'VIRTUAL',
    location: 'Zoom',
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
    endDate: '',
    status: 'draft',
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
    interestCount: 32,
    tags: ['guidance', 'Q&A'],
    featured: false,
  },
  {
    id: 'e3',
    title: 'Karachi Career Fair Booth',
    medium: 'IN_PERSON',
    location: 'Expo Center, Karachi',
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    endDate: '',
    status: 'past',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
    interestCount: 240,
    tags: ['fair'],
    featured: false,
  },
  {
    id: 'e4',
    title: 'Hybrid: Data Roles Info Session',
    medium: 'HYBRID',
    location: 'Head Office + Zoom',
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
    endDate: '',
    status: 'published',
    createdAt: Date.now() - 1000 * 60 * 60 * 30,
    interestCount: 51,
    tags: ['employer info', 'analytics'],
    featured: false,
  },
];
*/